### ISSUE TITLE
tMysqlConnectionPool use postgres driver

### ISSUE THREAD

**Issue by Taragolis** [jlolling/talendcomp_tDatabaseConnectionPool#1]
When I tried to use tMysqlConnectionPool componect I got error:
```
Exception in component tMysqlConnectionPool_1 (OPEN_MYSQL_CONNECTION_POOL)
java.lang.Exception: Could not load driver class: org.postgresql.Driver
	at de.cimt.talendcomp.connectionpool.BasicConnectionPool.loadDriver(BasicConnectionPool.java:96)
	at benchmarks.open_mysql_connection_pool_0_1.OPEN_MYSQL_CONNECTION_POOL.tMysqlConnectionPool_1Process(OPEN_MYSQL_CONNECTION_POOL.java:534)
	at benchmarks.open_mysql_connection_pool_0_1.OPEN_MYSQL_CONNECTION_POOL.runJobInTOS(OPEN_MYSQL_CONNECTION_POOL.java:967)
	at benchmarks.open_mysql_connection_pool_0_1.OPEN_MYSQL_CONNECTION_POOL.main(OPEN_MYSQL_CONNECTION_POOL.java:695)
Caused by: java.lang.ClassNotFoundException: org.postgresql.Driver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at de.cimt.talendcomp.connectionpool.BasicConnectionPool.loadDriver(BasicConnectionPool.java:93)
```

I found that on file `tMysqlConnectionPool/tMysqlConnectionPool_begin.javajet` at line 161 use Postgresql Driver:
```
<%=cid%>.loadDriver("org.postgresql.Driver");
```

**Comment by jlolling** [comment]
Damn copy & paste error!
